version: "3.9"
services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5000:5000"
    environment:
      LT_LOAD_ONLY: "en,pt,es,fr,de,it"
      LT_DISABLE_FILES: "true"
    command: ["--host", "0.0.0.0"]

  db:
    image: postgres:16
    container_name: translator-db
    restart: always
    environment:
      POSTGRES_DB: translator
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: translator-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-java
    depends_on:
      - libretranslate
      - db
    ports:
      - "8080:8080"
    environment:
      APP_BOOT_TOKEN: public-dev-boot-token-CHANGE_ME
      LIBRE_BASE_URL: http://libretranslate:5000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/translator
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      APP_OAUTH2_REDIRECT_URI: http://localhost:5173/oauth/callback
      JWT_SECRET: IntrMvLCt0wNl8AhgqtP017Y5vkvh4WgfLfsULHhN2MFAhjWcbKD5BXikOF7mf85

    volumes:
      - ../data:/app/data

volumes:
  pgdata: