version: "3.9"
services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5000:5000"
    environment:
      LT_LOAD_ONLY: "en,pt,es,fr,de,it"
      LT_DISABLE_FILES: "true"
    command: ["--host", "0.0.0.0"]

  backend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backend-java
      depends_on:
        - libretranslate
      ports:
        - "8080:8080"
      environment:
        # aponta o backend para o servi√ßo docker do LT
        LIBRE_BASE_URL: http://libretranslate:5000
        APP_STORAGE_UPLOAD_DIR: /app/data/uploads
        APP_STORAGE_OUTPUT_DIR: /app/data/outputs
        # se quiser habilitar logs detalhados:
        # LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      volumes:
        - ./data:/app/data